spring:
  datasource:
    username: loaf_store
    password: loaf_store
    url: jdbc:mysql://localhost:3306/loaf_store
   
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    defer-datasource-initialization: true
      
  sql:
    init:
      mode: always
         